#! /bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8

# Bspwm window configuration
bspc config border_width         3
bspc config window_gap           7

# General configuration
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Bspwm coloring
# Need to add stuff here


# Run polybar
$HOME/.config/polybar/scripts/launch.sh &

# Launch picom
picom &

